name: Test CI
on: [ push, fork ]

jobs:
  TEST_ALL:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: ğŸªœ Setup java 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: ğŸ¦ chmod /gradlew
        run:  chmod +x ./gradlew

      - name: ğŸ”¦ Tes ğŸš
        run: ./gradlew test --info
